[package]
name = "txn"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.53.1", features = ["full"] }
rust_decimal = { version = "1.43.0", features = ["serde", "macros"] }
chrono = { version = "0.4.45", features = ["serde"] }
thiserror = "2.0.21"
serde = { version = "1.0.229", features = ["derive"] }
dotenvy = "0.15.7"
axum = { version = "0.8.9", features = ["macros"] }
serde_json = "1.0.151"
http-body-util = "0.1.5"
tower = "0.5.3"
envconfig = "0.11.1"
uuid = { version = "1.27.0", features = ["v4"] }
futures = "0.3.34"
jsonwebtoken = { version = "11.1.0", features = ["aws_lc_rs"] }
argon2 = { version = "0.6.0", features = ["rand_core"] }
sha2 = "0.11.0"
secrecy = { version = "0.10.3", features = ["serde"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"]}
tower-http = { version = "0.7.1", features = ["trace", "request-id", "util"]}
metrics = "0.24.6"
metrics-exporter-prometheus = "0.18.3"

[dependencies.sqlx]
version = "0.9.0"
features = [
	"runtime-tokio",
	"postgres",
	"macros",
	"rust_decimal",
	"chrono"
]